-- ============================================================
-- V1: Initial schema - Cinema Booking System (Giai doan 1: monolith)
-- ============================================================

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(150)  NOT NULL,
    email         VARCHAR(150)  NOT NULL UNIQUE,
    password_hash VARCHAR(255),
    provider      VARCHAR(20)   NOT NULL DEFAULT 'LOCAL' CHECK (provider IN ('LOCAL', 'GOOGLE')),
    provider_id   VARCHAR(255),
    role          VARCHAR(20)   NOT NULL DEFAULT 'USER' CHECK (role IN ('USER', 'ADMIN')),
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE TABLE brands (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(150) NOT NULL,
    logo_url VARCHAR(500)
);

CREATE TABLE cinemas (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id BIGINT NOT NULL REFERENCES brands(id) ON DELETE CASCADE,
    name     VARCHAR(150) NOT NULL,
    address  VARCHAR(255),
    city     VARCHAR(100)
);
CREATE INDEX idx_cinemas_brand_id ON cinemas(brand_id);

CREATE TABLE rooms (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cinema_id BIGINT NOT NULL REFERENCES cinemas(id) ON DELETE CASCADE,
    name      VARCHAR(100) NOT NULL,
    room_type VARCHAR(20)  NOT NULL DEFAULT '2D'
);
CREATE INDEX idx_rooms_cinema_id ON rooms(cinema_id);

CREATE TABLE seat_types (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(50)  NOT NULL UNIQUE,
    price_multiplier NUMERIC(4,2) NOT NULL DEFAULT 1.00
);

CREATE TABLE seats (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id      BIGINT      NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    row_label    VARCHAR(5)  NOT NULL,
    col_number   INTEGER     NOT NULL,
    seat_type_id BIGINT      NOT NULL REFERENCES seat_types(id),
    UNIQUE (room_id, row_label, col_number)
);
CREATE INDEX idx_seats_room_id ON seats(room_id);

CREATE TABLE movies (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(255) NOT NULL,
    description  TEXT,
    duration_min INTEGER      NOT NULL,
    language     VARCHAR(50),
    release_date DATE,
    poster_url   VARCHAR(500),
    trailer_url  VARCHAR(500),
    status       VARCHAR(20) NOT NULL DEFAULT 'COMING_SOON'
                 CHECK (status IN ('NOW_SHOWING', 'COMING_SOON', 'ENDED')),
    view_count   BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE genres (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE movie_genres (
    movie_id BIGINT NOT NULL REFERENCES movies(id) ON DELETE CASCADE,
    genre_id BIGINT NOT NULL REFERENCES genres(id) ON DELETE CASCADE,
    PRIMARY KEY (movie_id, genre_id)
);

CREATE TABLE actors (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(150) NOT NULL,
    avatar_url VARCHAR(500)
);

CREATE TABLE movie_actors (
    movie_id  BIGINT NOT NULL REFERENCES movies(id) ON DELETE CASCADE,
    actor_id  BIGINT NOT NULL REFERENCES actors(id) ON DELETE CASCADE,
    role_name VARCHAR(150),
    PRIMARY KEY (movie_id, actor_id)
);

CREATE TABLE showtimes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id   BIGINT NOT NULL REFERENCES movies(id) ON DELETE CASCADE,
    room_id    BIGINT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    start_time TIMESTAMPTZ   NOT NULL,
    end_time   TIMESTAMPTZ   NOT NULL,
    base_price NUMERIC(10,2) NOT NULL
);
CREATE INDEX idx_showtimes_movie_id ON showtimes(movie_id);
CREATE INDEX idx_showtimes_room_id_start_time ON showtimes(room_id, start_time);

CREATE TABLE bookings (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users(id),
    showtime_id BIGINT NOT NULL REFERENCES showtimes(id),
    status      VARCHAR(20) NOT NULL DEFAULT 'PENDING'
                CHECK (status IN ('PENDING', 'PAID', 'CANCELLED', 'EXPIRED')),
    total_price NUMERIC(10,2) NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_bookings_user_id ON bookings(user_id);
CREATE INDEX idx_bookings_showtime_id ON bookings(showtime_id);

CREATE TABLE booking_seats (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    seat_id    BIGINT NOT NULL REFERENCES seats(id),
    price      NUMERIC(10,2) NOT NULL
);
CREATE INDEX idx_booking_seats_booking_id ON booking_seats(booking_id);
CREATE INDEX idx_booking_seats_seat_id ON booking_seats(seat_id);

CREATE TABLE payments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id      BIGINT NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    method          VARCHAR(30) NOT NULL DEFAULT 'FAKE_GATEWAY',
    status          VARCHAR(20) NOT NULL DEFAULT 'PENDING'
                    CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED')),
    transaction_ref VARCHAR(100),
    idempotency_key VARCHAR(100) NOT NULL UNIQUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_payments_booking_id ON payments(booking_id);

-- GHI CHU: Rang buoc chong ban trung ghe cung suat chieu (vi du: partial
-- unique index tren booking_seats, gioi han trong cac booking da PAID) se
-- duoc them o Tuan 3 khi flow giu ghe (Redis) va trang thai booking da on
-- dinh. Xem docs/ERD.md muc "Deferred constraints".
